### ISSUE TITLE
[fix] 바텀시트 페이지 컴포넌트 버튼 활성화 이슈

### ISSUE THREAD

**Issue by bigstar9906** [BangCrush/BankAI-Frontend#104]
## 📌 Feature

![image](https://github.com/BangCrush/BankAI-Frontend/assets/52996753/823bd219-d5db-4d7b-bb92-904fcd511679)

## 📜 To Do

- [ ] 각 바텀시트 페이지 버튼 활성화 여부 체크 및 활성화 작업 진행

**Comment by chaeyeon-yang** [comment]
> ## 📌 Feature
> ![image](https://private-user-images.githubusercontent.com/52996753/335645669-823bd219-d5db-4d7b-bb92-904fcd511679.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNzI0MTcsIm5iZiI6MTcxNzE3MjExNywicGF0aCI6Ii81Mjk5Njc1My8zMzU2NDU2NjktODIzYmQyMTktZDVkYi00ZDdiLWJiOTItOTA0ZmNkNTExNjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE2MTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOWU2MDJjMmM2MzZhMTIwN2MxNmY2Mjc2NWEwMGQwOTUxYTkxNzQ4ZmQwODIwYjlmNTliMjQ4YTFkZTg4ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.svoC4K0o5noIkgiUQzkVvSHMNOVhIlyfUD00GABpLOg)
> 
> ## 📜 To Do
> * [ ]  각 바텀시트 페이지 버튼 활성화 여부 체크 및 활성화 작업 진행

@bigstar9906 태규오빠 우리 비밀번호 입력 창 팝업 만들었어??

**Comment by bigstar9906** [comment]
> > ## 📌 Feature
> > ![image](https://private-user-images.githubusercontent.com/52996753/335645669-823bd219-d5db-4d7b-bb92-904fcd511679.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNzI0MTcsIm5iZiI6MTcxNzE3MjExNywicGF0aCI6Ii81Mjk5Njc1My8zMzU2NDU2NjktODIzYmQyMTktZDVkYi00ZDdiLWJiOTItOTA0ZmNkNTExNjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE2MTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOWU2MDJjMmM2MzZhMTIwN2MxNmY2Mjc2NWEwMGQwOTUxYTkxNzQ4ZmQwODIwYjlmNTliMjQ4YTFkZTg4ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.svoC4K0o5noIkgiUQzkVvSHMNOVhIlyfUD00GABpLOg)
> > 
> > ## 📜 To Do
> > * [ ]  각 바텀시트 페이지 버튼 활성화 여부 체크 및 활성화 작업 진행
> 
> @bigstar9906 태규오빠 우리 비밀번호 입력 창 팝업 만들었어??

**아직 못만들었으**..
키보드 켜야하는 버튼 온클릭에
windows.open(windows.location.origin+"/pwdKeyboard")
이런식으로 열고

NoLayoutRoutes에 pwdKeyboard 페이지 추가하고

해당 창에서 작성한 내용을 다시 창 호출한 쪽에 넘겨주게끔 하면 될것같은데
